# ---------------------------------
# N E O V I D E
#   config
# ---------------------------------
backtraces_path = "/home/moosicmaan/.config/neovide/neovide_backtraces.log" # see below for the default platform specific location
fork = false
frame = "full"
idle = true
maximized = false
mouse-cursor-icon = "arrow"
# neovim-bin = "/usr/bin/nvim" # in reality found dynamically on $PATH if unset
no-multigrid = false
srgb = false
tabs = true
theme = "auto"
title-hidden = true
vsync = true
wsl = false

# normal = ["OpenDyslexic Nerd Font Mono"]
[font]
normal = ["ComicShannsMono Nerd Font Mono"]
# normal = ["HeavyData Nerd Font"]
size = 24
