#!/usr/bin/awk -f

# This program prints a nice, friendly message.  It helps
# keep novice users from being afraid of the computer.
BEGIN { print "\nDon't Panic!\n\tDon't forget your towel.\n\t47" }


