#!/usr/bin/bash
# =====================================================
# -----------------------------------------------------
# Launch the statusbar for wayland compositors
#    Jason Bradberry (2024)
# -----------------------------------------------------
# =====================================================

# Prefix to run commands in wayland using uwsm.
PREFIX=$("$HOME/.config/.scripts/wayland-prefix")
themecache="$HOME/.cache/themestyle"
# Default theme: THEMEFOLDER;VARIATION
defaulttheme="moosic;moosic/mixed"

# -----------------------------------------------------
# Quit all running statuesbar instances
# -----------------------------------------------------
killall waybar
pkill waybar
pkill gBar
sleep 0.2

# -----------------------------------------------------
# Get current theme information from .cache/themestyle
# -----------------------------------------------------
if [ ! -f "$themecache" ]; then
  echo -e "Theme cache file, $themecache, not found! \nUsing default: $defaulttheme"
  touch "$themecache"
  echo "$defaulttheme" >"$themecache"
fi

themestyle=$(cat "$themecache")
echo "Using the following to open the bar(s): $themestyle"

IFS=';' read -ra arrThemes <<<"$themestyle"
echo "Theme: ${arrThemes[0]}"
echo "Style: ${arrThemes[1]}"

# -----------------------------------------------------
# Load gBar if selected
# -----------------------------------------------------
if [ -n "${arrThemes[0]}" ] && [ "${arrThemes[0]}" == "gBar" ]; then
  echo "Starting gBar..."
  notify-send -i "monitor" "Setting the statusbar to gBar"
  eval "${PREFIX}gBar bar 0" &
  # ${PREFIX}gBar bar 1 &
  exit 0
fi

# -----------------------------------------------------
# Loading the configuration for Waybar
# -----------------------------------------------------
config_file="config.jsonc"
style_file="style.css"

echo "Starting Waybar..."
eval "${PREFIX}waybar -c $HOME/.config/waybar/themes/${arrThemes[0]}/$config_file -s $HOME/.config/waybar/themes/${arrThemes[1]}/$style_file" &
