#!/usr/bin/bash
# =====================================================
# -----------------------------------------------------
# Turn off Hyprland animations and other effects for gaming
#    Jason Bradberry (2024)
# -----------------------------------------------------
# =====================================================

my_scripts="$HOME/.config/.scripts"
# /home/moosicmaan/.config/hypr/conf/winRules.conf
hypr_conf="$HOME/.config/hypr"

HYPRGAMEMODE=$(hyprctl getoption animations:enabled | awk 'NR==1{print $2}')
if [ "$HYPRGAMEMODE" = 1 ]; then
  cat "$hypr_conf"/conf/options/main/minimal.hyprland.conf >"$hypr_conf"/hyprland.conf
  /mnt/data/moosicmaan/CONFIG/.config/hypr/conf/options/main/minimal.hyprland.conf
  hyprctl --batch "\
        keyword animations:enabled 0;\
        keyword decoration:shadow:enabled 0;\
        keyword decoration:blur:enabled 0;\
        keyword general:gaps_in 0;\
        # keyword general:gaps_out 0;\
        keyword general:border_size 0;\
        keyword decoration:rounding 0;\
        keyword decoration:active_opacity 1;\
        keyword decoration:inactive_opacity 1;\
        keyword decoration:fullscreen_opacity 1"
  hyprctl keyword monitor "eDP-1, disable"
  pkill swww-daemon
  pkill waybar
  notify-send -i "nudity-symbolic" "GAME MODE" "ON"
  exit
else
  # hypr-barlaunch
  swww-daemon &
  "$my_scripts"/hypr-barlaunch &
  cat "$hypr_conf"/conf/options/main/moosic.hyprland.conf >"$hypr_conf"/hyprland.conf
  notify-send -i "nudity-none-symbolic" "GAME MODE" "OFF"
fi
hyprctl reload
