#!/usr/bin/bash
# =====================================================
# -----------------------------------------------------
# Launch the statusbar selector for wayland compositors
#    Jason Bradberry (2024)
# -----------------------------------------------------
# =====================================================

# use the following when there are a number of non-waybar themes to concider
# themes_path="$HOME/.config/.settings/barthemes/"
themes_path="$HOME/.config/waybar/themes/"

# Initialize theme lists
declare -a theme_list
declare -a theme_names

# -----------------------------------------------------
# Read available themes
# -----------------------------------------------------
while IFS= read -r theme_dir; do
  [[ "$theme_dir" == "$themes_path/assets" || "$theme_dir" == "$themes_path" ]] && continue
  [[ $(find -L "$theme_dir" -maxdepth 1 -type d | wc -l) -ne 1 ]] && continue

  # Extract relative theme path
  rel_path="${theme_dir#"$themes_path"}" # Remove base path
  first_folder="${rel_path%/*}"          # Get first directory name
  if [ "$first_folder" == "" ]; then     # For configs in the base theme folder
    first_folder="$rel_path"
  fi
  formatted_theme="$first_folder;$rel_path"

  config_path="$theme_dir/config.sh"

  if [[ -f "$config_path" ]]; then
    source "$config_path"
    theme_names+=("$theme_name")
    echo "Sourcing config for $config_path"
  else
    theme_names+=("$formatted_theme")
  fi

  theme_list+=("$formatted_theme")
done < <(find -L "$themes_path" -maxdepth 2 -type d)

# -----------------------------------------------------
# Show selection menu with rofi
# -----------------------------------------------------
choice=$(printf "%s\n" "${theme_names[@]}" | rofi -dmenu -i -replace \
  -config ~/.config/rofi/config-narrow.rasi -no-show-icons -width 30 -p "Themes" -format i)

# -----------------------------------------------------
# Apply selected theme
# -----------------------------------------------------
if [[ -n "$choice" ]]; then
  echo "Loading waybar theme..."
  echo "${theme_list[choice]}" >"$HOME/.cache/themestyle"
  "$HOME/.config/.scripts/hypr-barlaunch"
fi
