#!/usr/bin/bash
# =====================================================
# -----------------------------------------------------
# Turn off Hyprland animations and other effects for gaming
#    Jason Bradberry (2024)
# -----------------------------------------------------
# =====================================================

my_scripts="$HOME/.config/.scripts"
hypr_conf="$HOME/.config/hypr/conf"

HYPRGAMEMODE=$(hyprctl getoption animations:enabled | awk 'NR==1{print $2}')
if [ "$HYPRGAMEMODE" = 1 ]; then
  hyprctl --batch "\
        keyword animations:enabled 0;\
        keyword decoration:shadow:enabled 0;\
        keyword decoration:blur:enabled 0;\
        keyword general:gaps_in 0;\
        keyword general:gaps_out 0;\
        keyword general:border_size 0;\
        keyword decoration:rounding 0;\
        keyword decoration:active_opacity 1;\
        keyword decoration:inactive_opacity 1;\
        keyword decoration:fullscreen_opacity 1"
  hyprctl keyword monitor "eDP-1, disable"
  pkill swww-daemon
  pkill waybar
  "mv $hypr_conf/winRules.conf $hypr_conf/winRules.conf.bak"
  notify-send -i "bell" "GAME MODE" "ON"
  exit
else
  # hypr-barlaunch
  swww-daemon &
  "$my_scripts"/hypr-barlaunch &
  "mv $hypr_conf/winRules.conf.bak $hypr_conf/winRules.conf"
  notify-send -i "bell" "GAME MODE" "OFF"
fi
hyprctl reload
