#!/bin/bash

PREFIX=$("$HOME/.config/.scripts/wayland-prefix")

newwall=$1

echo "$newwall" >"$HOME"/.cache/current_wallpaper
eval "${PREFIX}swww img" "$newwall" &
"$HOME"/.config/.scripts/ut-wallpaper init
