#!/usr/bin/bash
# =====================================================
# -----------------------------------------------------
# Reload Monitors
# Script to reload monitors when working with multiple ttys.
# Useful for when you have a laptop and docked setup.
# Work-around for Wayland bug where monitors are not
# detected properly when switching ttys.
#     Jason Bradberry (2024)
# -----------------------------------------------------
# =====================================================

mv "$HOME/.config/hypr/conf/monitor.conf" "$HOME/.config/hypr/conf/monitor.conf.bak"
echo "monitor=,preferred,auto,auto" >"$HOME/.config/hypr/conf/monitor.conf"
hyprctl reload
sleep 3
rm "$HOME/.config/hypr/conf/monitor.conf"
mv "$HOME/.config/hypr/conf/monitor.conf.bak" "$HOME/.config/hypr/conf/monitor.conf"
hyprctl reload
