#!/bin/bash
# =====================================================
# -----------------------------------------------------
# Script called from yazi to set the wallpaper
#     Jason Bradberry (2024)
# -----------------------------------------------------
# =====================================================

PREFIX=$("$HOME/.config/.scripts/wayland-prefix")

newwall=$1

echo "$newwall" >"$HOME"/.cache/current_wallpaper
eval "${PREFIX}swww img" "$newwall" &
"$HOME"/.config/.scripts/ut-wallpaper init
