#!/bin/bash
# =====================================================
# -----------------------------------------------------
# Launch the statusbar for wayland compositors
#    Jason Bradberry (2024)
# -----------------------------------------------------
# =====================================================

# Prefix to run commands in wayland using uwsm.
PREFIX=$("$HOME/.config/.scripts/wayland-prefix")
themecache="$HOME/.cache/themestyle"

# -----------------------------------------------------
# Quit all running statuesbar instances
# -----------------------------------------------------
killall waybar
pkill waybar
pkill gBar
sleep 0.2

# -----------------------------------------------------
# Default theme: /THEMEFOLDER;/VARIATION
# -----------------------------------------------------
themestyle="/moosic;/moosic/mixed"

# -----------------------------------------------------
# Get current theme information from .cache/themestyle
# -----------------------------------------------------
if [ -f "$themecache" ]; then
  themestyle=$(cat "$themecache")
else
  touch "$themecache"
  echo "$themestyle" >"$themecache"
fi

IFS=';' read -ra arrThemes <<<"$themestyle"
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
echo "Theme: ${arrThemes[0]}"

if [ ! -f "$HOME/.config/waybar/themes${arrThemes[1]}/style.css" ]; then
  themestyle="/moosic;/moosic/mixed"
fi

echo "Using themestyle: $themestyle"

# -----------------------------------------------------
# Load gBar if selected
# -----------------------------------------------------
if [ -n "${arrThemes[0]}" ] && [ "${arrThemes[0]}" == "/gBar" ]; then
  eval "${PREFIX}gBar bar 0" &
  # ${PREFIX}gBar bar 1 &
  notify-send "Set the statusbar to gBar"
  exit 1
fi

# -----------------------------------------------------
# Loading the configuration for Waybar
# -----------------------------------------------------
config_file="config.jsonc"
style_file="style.css"

# Standard files can be overwritten with an existing config-custom or style-custom.css
if [ -n "${arrThemes[0]}" ] && [ -f "$HOME/.config/waybar/themes/${arrThemes[0]}/config-custom" ]; then
  config_file="config-custom"
fi

if [ -n "${arrThemes[1]}" ] && [ -f "$HOME/.config/waybar/themes/${arrThemes[1]}/style-custom.css" ]; then
  style_file="style-custom.css"
fi

eval "${PREFIX}waybar -c $HOME/.config/waybar/themes${arrThemes[0]}/$config_file -s $HOME/.config/waybar/themes${arrThemes[1]}/$style_file" &
