#!/bin/bash
# =====================================================
# -----------------------------------------------------
# From:
# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  ##
# Scripts for volume controls for audio and mic
#     Modified by: Jason Bradberry (2024)
# -----------------------------------------------------
# =====================================================

iDIR="/usr/share/icons/Tela-circle-dracula-dark/symbolic/status"

# Get Volume
get_volume() {
  volume=$(pamixer --get-volume)
  if [[ "$volume" -eq "0" ]]; then
    echo "Muted"
  else
    echo "$volume"
  fi
}

get_icon() {
  current=$(get_volume)
  if [[ "$current" == "Muted" ]]; then
    echo "$iDIR/audio-volume-muted-symbolic.svg"
  elif [[ "$current" -le 33 ]]; then
    echo "$iDIR/audio-volume-low-symbolic.svg"
  elif [[ "$current" -le 66 ]]; then
    echo "$iDIR/audio-volume-medium-symbolic.svg"
  elif [[ "$current" -le 100 ]]; then
    echo "$iDIR/audio-volume-high-symbolic.svg"
  else
    echo "$iDIR/audio-volume-overamplified-symbolic.svg"
  fi
}

# Send notification
notify_user() {
  volume=$(get_volume)
  icon=$(get_icon)
  id_file="/tmp/volume_notify_id"
  [[ -f $id_file ]] && id=$(<"$id_file") || id=0

  if [[ "$volume" == "Muted" ]]; then
    id=$(notify-send -p -r "$id" \
      -u normal \
      -i "$icon" \
      "Volume: Muted")
  else
    id=$(notify-send -p -r "$id" \
      -h int:value:"$volume" \
      -u normal \
      -i "$icon" \
      "Volume: ${volume}%")
  fi

  echo "$id" >"$id_file"
}

# Increase Volume
inc_volume() {
  if [ "$(pamixer --get-mute)" == "true" ]; then
    toggle_mute
  else
    pamixer -i 5 --allow-boost --set-limit 150 && notify_user
  fi
}

# Decrease Volume
dec_volume() {
  if [ "$(pamixer --get-mute)" == "true" ]; then
    toggle_mute
  else
    pamixer -d 5 && notify_user
  fi
}

# Toggle Mute
toggle_mute() {
  if [ "$(pamixer --get-mute)" == "false" ]; then
    pamixer -m && notify-send -e -u normal -i "$iDIR/audio-volume-muted-symbolic.svg" "Volume Switched OFF"
  elif [ "$(pamixer --get-mute)" == "true" ]; then
    pamixer -u && notify-send -e -u normal -i "$(get_icon)" "Volume Switched ON"
  fi
}

# Toggle Mic
toggle_mic() {
  if [ "$(pamixer --default-source --get-mute)" == "false" ]; then
    pamixer --default-source -m && notify-send -e -u normal -i "$iDIR/audio-input-microphone-muted-symbolic.svg" "Microphone Switched OFF"
  elif [ "$(pamixer --default-source --get-mute)" == "true" ]; then
    pamixer -u --default-source u && notify-send -e -u normal -i "$iDIR/audio-input-microphone-high-symbolic.svg""Microphone Switched ON"
  fi
}

# Get Mic Icon
get_mic_icon() {
  current=$(pamixer --default-source --get-volume)
  if [[ "$current" -eq "0" ]]; then
    echo "$iDIR/audio-input-microphone-muted-symbolic.svg"
  else
    echo "$iDIR/audio-input-microphone-high-symbolic.svg"
  fi
}

# Get Microphone Volume
get_mic_volume() {
  volume=$(pamixer --default-source --get-volume)
  if [[ "$volume" -eq "0" ]]; then
    echo "Muted"
  else
    echo "$volume%"
  fi
}

# Notify for Microphone
notify_mic_user() {
  volume=$(get_mic_volume)
  icon=$(get_mic_icon)
  notify-send -e -h int:value:"$volume" -h "string:x-canonical-private-synchronous:volume_notif" -u normal -i "$icon" "Mic-Level: $volume"
}

# Increase MIC Volume
inc_mic_volume() {
  if [ "$(pamixer --default-source --get-mute)" == "true" ]; then
    toggle_mic
  else
    pamixer --default-source -i 5 && notify_mic_user
  fi
}

# Decrease MIC Volume
dec_mic_volume() {
  if [ "$(pamixer --default-source --get-mute)" == "true" ]; then
    toggle-mic
  else
    pamixer --default-source -d 5 && notify_mic_user
  fi
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
  get_volume
elif [[ "$1" == "--inc" ]]; then
  inc_volume
elif [[ "$1" == "--dec" ]]; then
  dec_volume
elif [[ "$1" == "--toggle" ]]; then
  toggle_mute
elif [[ "$1" == "--toggle-mic" ]]; then
  toggle_mic
elif [[ "$1" == "--get-icon" ]]; then
  get_icon
elif [[ "$1" == "--get-mic-icon" ]]; then
  get_mic_icon
elif [[ "$1" == "--mic-inc" ]]; then
  inc_mic_volume
elif [[ "$1" == "--mic-dec" ]]; then
  dec_mic_volume
else
  get_volume
fi
