#!/usr/bin/env bash
# =====================================================
# -----------------------------------------------------
# nmtui-colors
#     Modified by: Jason Bradberry (2024)
# -----------------------------------------------------
# =====================================================

NEWT_COLORS='
  window=white,red
  border=white,red
  checkbox=white,red
  actcheckbox=white,green
' nmtui
