#!/bin/bash
# =====================================================
# -----------------------------------------------------
# From:
#     Bookmarks
#     by Stephan Raabe (2023)
#     Modified by: Jason Bradberry (2024)
# Loads browser bookmarks in rofi
# -----------------------------------------------------
# =====================================================

selected=$(grep '"url":' <~/.config/BraveSoftware/Brave-Browser/Default/Bookmarks | awk '{print $2}' | sed 's/"//g' | rofi -dmenu -config ~/.config/rofi/config-wide.rasi -p "Select a Brave Bookmark")

if [ "$selected" ]; then
  brave "$selected"
fi
