#!/usr/bin/bash

BA_CATS=$(pacman -Sg | grep blackarch)

CAT_SEL=$(echo "$BA_CATS" | sort | rofi -dmenu -config "$HOME/.config/rofi/config.rasi")

CAT_APPS=$(pacman -Sg "$CAT_SEL" | awk '{print $2}' | xargs -r pacman -Si | awk -F ': ' '/^Name/ {name=$2} /^Description/ {print name ": " $2}')

APP_SEL=$(echo "$CAT_APPS" | sort | rofi -dmenu -config "$HOME/.config/rofi/config-wide.rasi")

APP_NAME=$(echo "$APP_SEL" | awk -F ': ' '{print $1}')

if pacman -Q "$APP_NAME" &>/dev/null; then
  "$APP_NAME"
else
  kitty -e sh -c "sudo pacman -S $APP_NAME"
fi
