#!/bin/sh
# =====================================================
# -----------------------------------------------------
# From: I cannot remember where I got this script from.
# Display the current monitor brightness
#     Modified by: Jason Bradberry (2024)
# -----------------------------------------------------
# =====================================================

case $BLOCK_BUTTON in
1) /mnt/data/moosicmaan/CONFIG/.config/.scripts/ut-monbrightness --dec & ;;
3) /mnt/data/moosicmaan/CONFIG/.config/.scripts/ut-monbrightness --inc & ;;
2)
  notify-send "💡 Brightness module" "\- Shows current brightness level ☀️."
  ;;
6)
  setsid -f "$TERMINAL" -e "$EDITOR" "$0"
  ;;
esac

# current brightness
# curr_brightness=$(cat /sys/class/backlight/*/brightness)

# max_brightness
# max_brightness=$(cat /sys/class/backlight/*/max_brightness)

# brightness percentage
# brightness_per=$((100 * curr_brightness / max_brightness))
brightness_per=$(/mnt/data/moosicmaan/CONFIG/.config/.scripts/ut-monbrightness --get)

echo " 💡${brightness_per}%"
