#!/bin/bash
# =====================================================
# -----------------------------------------------------
# From: I cannot remember where I got this script from.
# Display the current time and date in a nice format.
#     Modified by: Jason Bradberry (2024)
# -----------------------------------------------------
# =====================================================

clock=$(date '+%I')

# case "$clock" in
# "00") icon="🕛" ;;
# "01") icon="🕐" ;;
# "02") icon="🕑" ;;
# "03") icon="🕒" ;;
# "04") icon="🕓" ;;
# "05") icon="🕔" ;;
# "06") icon="🕕" ;;
# "07") icon="🕖" ;;
# "08") icon="🕗" ;;
# "09") icon="🕘" ;;
# "10") icon="🕙" ;;
# "11") icon="🕚" ;;
# "12") icon="🕛" ;;
# esac

case "$clock" in
"00") icon="󱑖" ;;
"01") icon="󱑋" ;;
"02") icon="󱑌" ;;
"03") icon="󱑍" ;;
"04") icon="󱑎" ;;
"05") icon="󱑏" ;;
"06") icon="󱑐" ;;
"07") icon="󱑑" ;;
"08") icon="󱑒" ;;
"09") icon="󱑓" ;;
"10") icon="󱑔" ;;
"11") icon="󱑕" ;;
"12") icon="󱑖" ;;
esac

case $BLOCK_BUTTON in
1) notify-send "This Month" "$(cal | sed "s/\<$(date +'%e' | tr -d ' ')\>/<b><span color='red'>&<\/span><\/b>/")" && notify-send "Appointments" "$(calcurse -d3)" ;;
2) setsid -f kitty -e calcurse ;;
3) notify-send "📅 Time/date module" "\- Left click to show upcoming appointments for the next three days via \`calcurse -d3\` and show the month via \`cal\`
- Middle click opens calcurse if installed" ;;
6) setsid -f "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

# date "+%Y %b %d (%a) $icon %I:M%p"
# date "+%a, %b %d $icon %I:%M%p"
icon="🕒"
# printf "| %s %s %s      -SYSTRAY-      \n" "$(date '+%a, %b %d')" "$icon" "$(date '+%I:%M%p')"
printf " %s %s %s\n" "$(date '+%a, %b %d')" "$icon" "$(date '+%I:%M%p  ')"
