#!/bin/sh
# Display the average CPU load.
TERMINAL="kitty"
case "$BLOCK_BUTTON" in
1) notify-send "🖥 CPU hogs" "$(ps axch -o cmd:15,%cpu --sort=-%cpu | head)\\n(100% per core)" ;;
2) setsid -f "$TERMINAL" -e btop ;;
3) notify-send "🖥 CPU load module " "\- Shows the average CPU load.
 Click to show intensive processes.
- Middle click to open btop." ;;
6) terminal -e "$EDITOR" "$0" ;;
esac

THRESHOLD=5

load=$(cut -d' ' -f1 /proc/loadavg)

is_threshold_exceeded="$(echo "$load > $THRESHOLD" | bc)"
[ "$is_threshold_exceeded" -eq 1 ] && color=9

. sb-theme
display " $load" "$color"
