#!/usr/bin/env bash
# =====================================================
# -----------------------------------------------------
# From: I cannot remember where I got this script from.
# Shows the current moon phase.
#     Modified by: Jason Bradberry (2024)
# -----------------------------------------------------
# =====================================================

# moonfile="${XDG_DATA_HOME:-$HOME/.local/share}/moonphase"
moonfile="${XDG_CACHE_HOME:-$HOME/.cache}/moonphase"

# [ -s "$moonfile" ] && [ "$(stat -c %y "$moonfile" 2>/dev/null | cut -d' ' -f1)" = "$(date '+%Y-%m-%d')" ] ||
{ curl -m 10 -sf "wttr.in/?format=%m" >"$moonfile" || exit 1; }

icon="$(cat "$moonfile")"

case "$icon" in
🌑) name="New" ;;
🌒) name="Waxing Crescent" ;;
🌓) name="First Quarter" ;;
🌔) name="Waxing Gibbous" ;;
🌕) name="Full" ;;
🌖) name="Waning Gibbous" ;;
🌗) name="Last Quarter" ;;
🌘) name="Waning Crescent" ;;
*) exit 1 ;;
esac

echo " ${icon-?}"

case $BLOCK_BUTTON in
3) notify-send "🌜 Moon phase module" "Displays current moon phase.
- 🌑: New
- 🌒: Waxing Crescent
- 🌓: First Quarter
- 🌔: Waxing Gibbous
- 🌕: Full
- 🌖: Waning Gibbous
- 🌗: Last Quarter
- 🌘: Waning Crescent" ;;
6) setsid -f "$TERMINAL" -e "$EDITOR" "$0" ;;
esac
