#!/bin/sh
# Display currently playing music.

case "$BLOCK_BUTTON" in
1) "$HOME"/.config/.scripts/media-ctrl --prv ;;
2) "$HOME"/.config/.scripts/media-ctrl --pause ;;
3) "$HOME"/.config/.scripts/media-ctrl --nxt ;;
4) "$HOME"/.config/.scripts/media-ctrl --stop ;;
esac

set -- --player=spotube,mpv,%any
icon="󰐊"
paused_icon="󰏤"
if status="$(playerctl "$@" status 2>&1)" && [ "$status" != "Stopped" ]; then
  [ "$status" = "Paused" ] && icon="$paused_icon"

  song="$(playerctl "$@" metadata --format "{{playerName}} {{duration(position)}}|{{duration(mpris:length)}}: {{title}}, {{artist}}")"

# else
#   [ "$(mpc status "%state%")" = "paused" ] && icon="$paused_icon"
#
#   song="$(mpc current --format="%title%[ - %artist%]")"
fi

[ -z "$song" ] && exit

. "$HOME"/.config/.scripts/sb-theme
display "$icon $song"
