#!/bin/sh
# =====================================================
# -----------------------------------------------------
# From: I cannot remember where I got this script from.
# Display currently playing music.
#     Modified by: Jason Bradberry (2024)
# -----------------------------------------------------
# =====================================================

case "$BLOCK_BUTTON" in
1) "$HOME"/.config/.scripts/media-ctrl --prv ;;
2) "$HOME"/.config/.scripts/media-ctrl --pause ;;
3) "$HOME"/.config/.scripts/media-ctrl --nxt ;;
4) "$HOME"/.config/.scripts/media-ctrl --stop ;;
esac

set -- --player=spotube,mpv,%any
icon="󰐊"
paused_icon="󰏤"
if status="$(playerctl "$@" status 2>&1)" && [ "$status" != "Stopped" ]; then
  [ "$status" = "Paused" ] && icon="$paused_icon"

  # song="$(playerctl "$@" metadata --format "{{playerName}} {{duration(position)}}:{{duration(mpris:length)}}: {{title}}, {{artist}}")"
  song="$(playerctl "$@" metadata --format "{{duration(position)}}/{{duration(mpris:length)}} {{title}},{{artist}}")"
fi

[ -z "$song" ] && exit

. "$HOME"/.config/.scripts/sb-theme
# display "$icon $song"
display "$(printf '%.69s' "$icon $song")"

# display "$(printf '%.79s' "\x1b[33m$icon \x1b[32m$song\x1b[0m")"
# printf '%.79s' "$icon $song"
