#!/usr/bin/bash
# =====================================================
# -----------------------------------------------------
# From: I cannot remember where I got this script from.
# Display currently playing music.
#     Modified by: Jason Bradberry (2024)
# -----------------------------------------------------
# =====================================================

wpctl() {
  arg="$2"

  set -- "$1"
  if [ "$1" = set-volume ]; then
    set -- "$@" --limit=1.0
  fi

  set -- "$@" @DEFAULT_AUDIO_SINK@ "$arg"

  command wpctl "$@"
}

case "$BLOCK_BUTTON" in
3) "$HOME"/.config/.scripts/media-vol --inc ;;
1) "$HOME"/.config/.scripts/media-vol --dec ;;
2) "$HOME"/.config/.scripts/media-vol --toggle ;;
6) terminal -e "$EDITOR" "$0" ;;
esac

. "$HOME"/.config/.scripts/sb-theme
if wpctl get-volume | grep -q "[MUTED]"; then
  display " 🔇 M " 9
  exit
fi

volume_frac="$(wpctl get-volume | cut -d' ' -f2)"
volume="$(echo "$volume_frac * 100 / 1" | bc)"

if [ -z "$volume" ]; then
  exit 1
fi

if [ "$volume" -gt 66 ]; then
  icon="🔊"
elif [ "$volume" -gt 33 ]; then
  icon="🔉"
else
  icon="🔈️"
fi

display " $icon$volume%"
# echo -e "  \x04$icon$volume%"
