#!/bin/bash
# =====================================================
# -----------------------------------------------------
# Sets the screen temperature based on the current time.
#     Jason Bradberry (2024)
# -----------------------------------------------------
# =====================================================

PREFIX=$("$HOME/.config/.scripts/wayland-prefix")

CONTENT=$(curl -s http://ip-api.com/json/)
longitude=$(echo "$CONTENT" | jq .lon)
latitude=$(echo "$CONTENT" | jq .lat)
${PREFIX}wlsunset -l "$latitude" -L "$longitude"
