#!/bin/bash

PREFIX=$("$HOME/.config/.scripts/wayland-prefix.sh")

CONTENT=$(curl -s http://ip-api.com/json/)
longitude=$(echo $CONTENT | jq .lon)
latitude=$(echo $CONTENT | jq .lat)
${PREFIX}wlsunset -l $latitude -L $longitude
