#!/usr/bin/env bash
# =====================================================
# -----------------------------------------------------
# Sets the screen temperature based on the current time.
#     Jason Bradberry (2024)
# -----------------------------------------------------
# =====================================================

prifix=$("$HOME/.config/.scripts/wayland-prefix")

content=$(curl -s http://ip-api.com/json/)
longitude=$(echo "$content" | jq .lon)
latitude=$(echo "$content" | jq .lat)
"${prifix}"wlsunset -l "$latitude" -l "$longitude"
