#!/usr/bin/env bash
# =====================================================
# -----------------------------------------------------
# Display the file types of each item in a directory
#    Jason Bradberry (2025)
# -----------------------------------------------------
# =====================================================

if (($# > 0)); then
    fname_array=("$@")
else
    shopt -s nullglob
    fname_array=(* .*)
    shopt -u nullglob
fi

file "${fname_array[@]}" 2>/dev/null |
    awk 'NR % 2 == 1 {print "\033[1;36m" $0 "\033[0m"} NR % 2 == 0 {print $0}' |
    bat --force-colorization
