#!/bin/bash
# =====================================================
# -----------------------------------------------------
# From:
# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  ##
# Script for screen backlights (if supported) using brightnessctl
#     Modified by Jason Bradberry (2024)
# -----------------------------------------------------
# =====================================================

# iDIR="/usr/share/icons/Papirus-Dark/symbolic/status"
iDIR="/usr/share/icons/Tela-circle-dracula-dark/symbolic/status"
# notification_timeout=1000
step=5 # INCREASE/DECREASE BY THIS VALUE

# Get brightness
get_backlight() {
  brightnessctl -m | cut -d, -f4 | sed 's/%//'
}

# Get icons
get_icon() {
  current=$(get_backlight)
  echo "Current brightness: $current"
  if [ "$current" -le 10 ]; then
    icon="$iDIR/display-brightness-off-symbolic.svg"
  elif [ "$current" -le 30 ]; then
    icon="$iDIR/display-brightness-low-symbolic.svg"
  elif [ "$current" -le 60 ]; then
    icon="$iDIR/display-brightness-medium-symbolic.svg"
  elif [ "$current" -gt 75 ]; then
    icon="$iDIR/display-brightness-high-symbolic.svg"
  else
    icon="$iDIR/display-brightness-symbolic.svg"
  fi
}

# Notify
notify_user() {
  echo "$icon" "$current%"
  notify-send -i "$icon" "Brightness : $current%"
}

# Change brightness
change_backlight() {
  local current_brightness
  current_brightness=$(get_backlight)

  # Calculate new brightness
  if [[ "$1" == "+${step}%" ]]; then
    new_brightness=$((current_brightness + step))
  elif [[ "$1" == "${step}%-" ]]; then
    new_brightness=$((current_brightness - step))
  fi

  # Ensure new brightness is within valid range
  if ((new_brightness < 0)); then
    new_brightness=0
  elif ((new_brightness > 100)); then
    new_brightness=100
  fi

  brightnessctl set "${new_brightness}%"
  get_icon
  current=$new_brightness
  notify_user
}

# Execute accordingly
case "$1" in
"--get")
  get_backlight
  ;;
"--inc")
  change_backlight "+${step}%"
  ;;
"--dec")
  change_backlight "${step}%-"
  ;;
*)
  get_backlight
  ;;
esac
