#!/usr/bin/env bash

# Cleanup old modules
pactl unload-module module-null-sink 2>/dev/null
pactl unload-module module-remap-source 2>/dev/null

# Create virtual sink
pactl load-module module-null-sink \
  sink_name=MoosSink \
  sink_properties=device.description="Moos_Sink"

# Create virtual source from its monitor
pactl load-module module-remap-source \
  master=MoosSink.monitor \
  source_name=MoosSource \
  source_properties=device.description="Moos_Source"
