#!/usr/bin/bash

# pgrep -f "kitty --class bluet" \
#   && pkill -f "kitty--class bluet" \
#   || kitty --class bluet -e bluetui

term="$1"
class="$2"
prog="$3"

pkill -f "$term --class $class" ||
  "$term" --class "$class" -e "$prog"
