#!/usr/bin/env bash
# =====================================================
# -----------------------------------------------------
# Script to toggle a ter/class combination like a
# scratpad
#    Jason Bradberry (2026)
# -----------------------------------------------------
# =====================================================

# pgrep -f "kitty --class bluet" \
#   && pkill -f "kitty--class bluet" \
#   || kitty --class bluet -e bluetui

term="$1"
class="$2"
prog="$3"

pkill -f "$term --class $class" ||
  "$term" --class "$class" -e "$prog"
