#!/usr/bin/env bash
# =====================================================
# -----------------------------------------------------
# Reload, Select, or Randomly Select the wallpaper and colorscheme
#    Jason Bradberry (2025)
# -----------------------------------------------------
# =====================================================
# Cache file for holding the current wallpaper
cache_file="$HOME/.cache/current_wallpaper"
rasi_file="$HOME/.cache/current_wallpaper.rasi"
pic_folder="$HOME/Pictures/Backgrounds"

# Create cache file if none exists
if [ ! -f "$cache_file" ]; then
  echo "$pic_folder/default.png" >"$cache_file"
fi

# Create rasi file if not exists
if [ ! -f "$rasi_file" ]; then
  echo "* { current-image: url(\"$pic_folder/default.png\", height); }" >"$rasi_file"
fi

case $1 in
# Load wallpaper from .cache of last session
"--init")
  # if [ -f "$cache_file" ]; then
  cwall=$(cat "$cache_file") >/dev/null 2>&1
  echo "Debug in --init: cwall = $cwall"
  wal -q -i "$cwall"
  # else
  # wal -q -i ~/Pictures/
  # fi
  ;;

# Select wallpaper with rofi
"--select")
  selected=$(find "$pic_folder" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" \) -exec basename {} \; | sort -R | while read -r rfile; do
    echo -en "$rfile\x00icon\x1f$pic_folder/${rfile}\n"
  done | rofi -dmenu -replace -config ~/.config/rofi/config-wall.rasi -p " > ")
  if [ ! "$selected" ]; then
    echo "No wallpaper selected"
    exit
  fi
  echo "Debug in --select: selected = $selected"
  wal -q -i "$pic_folder/$selected" >/dev/null 2>&1
  ;;
# Use the file they sent
"--file")
  echo "Debugin --file: 2 = $2"
  wal -q -i "$2" >/dev/null 2>&1
  ;;

# Randomly select wallpaper for everything else
*)
  wal -q -i "$pic_folder/" >/dev/null 2>&1
  ;;
esac

# -----------------------------------------------------
# Load current pywal color scheme
# -----------------------------------------------------
source /home/moosicmaan/.cache/wal/colors.sh
# source "$HOME"/.cache/wal/colors.sh
echo ":: Wallpaper: $wallpaper"

# -----------------------------------------------------
# Write selected wallpaper into .cache files
# -----------------------------------------------------
echo "$wallpaper" >"$cache_file"
echo "* { current-image: url(\"$wallpaper\", height); }" >"$rasi_file"

# -----------------------------------------------------
# get wallpaper image name
# -----------------------------------------------------
newwall=$(echo "$wallpaper" | sed "s|$pic_folder/||g")

# -----------------------------------------------------
# transition_type="wipe"
# transition_type="outer"
transition_type="any"

swww img "$wallpaper" \
  --transition-type=$transition_type
# --transition-pos "$(hyprctl cursorpos)"

# swww img "$wallpaper"
# --transition-bezier .43,1.19,1,.4 \
# --transition-fps=60 \
# --transition-type=$transition_type \
# --transition-duration=0.7 \
# --transition-pos "$(hyprctl cursorpos)"o

# -----------------------------------------------------
# Reload waybar with new colors
# -----------------------------------------------------
"$HOME/.config/.scripts/hypr-barlaunch"

# -----------------------------------------------------
# Send notification
# -----------------------------------------------------

if [ "$1" == "init" ]; then
  echo ":: Init"
else
  sleep 1
  notify-send --icon=preferences "Colors and Wallpaper updated" "with image $newwall"
fi

echo "DONE"
