#!/bin/bash
# =====================================================
# -----------------------------------------------------
# Script to populate the prefix for wayland app launching
# using uwsm
# Will also do various things based on backend
# if the calling program cannot do it itself
#     Jason Bradberry (2024)
# -----------------------------------------------------
# =====================================================

if [[ -n "$UWSM_SESSION" ]]; then
  # notify-send --icon="alarm" "UWSM_SESSION=true" "PREFIX: uwsm app -- "
  echo "uwsm app -- "
else
  echo ""
fi
