#!/usr/bin/env bash
# =====================================================
# -----------------------------------------------------
# Script called from yazi to set the wallpaper
#     Jason Bradberry (2024)
# -----------------------------------------------------
# =====================================================

new_wallp=$1

"$HOME"/.config/.scripts/ut-wallpaper --file "$new_wallp"
