# -----------------------------------------------------
# Autostart:
# -----------------------------------------------------
# --> generally not needed when using uwsm - should all be taken care of by SystemD services <--
# Start Polkit
# exec --no-startup-id /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# exec /usr/lib/polkit-kde-authentication-agent-1
# exec --no-startup-id /usr/lib/hyprpolkitagent/hyprpolkitagent &
exec-once=/usr/lib/hyprpolkitagent/hyprpolkitagent
# exec systemctl restart polkit

# added to make sure dolphin plays nice and opens files with the right program
# env = XDG_MENU_PREFIX,arch-

# Setup XDG for screen sharing
# exec $HOME/.config/.scripts/start-xdg

# Load GTK settings
# exec $HOME/.config/.scripts/start-gtk
#
exec-once=dunst
# Using swayidle to start swaylock
exec-once=swayidle -w timeout 900 'swaylock -f -c 000000' timeout 1600 'swaymsg "output * power off"' resume 'swaymsg "output * power on"' before-sleep 'swaylock -f -c 000000'

# Load cliphist history
exec-once=wl-paste --watch cliphist store

# Start EMACS Server
# exec-once = /usr/bin/emacs --daemon=serve

# # Initialize swww
exec-once=swww query || swww-daemon

# Startup the system tray applets:
# exec nm-tray
# exec pasystray
exec-once=garuda-system-maintenance
# exec blueman-applet
exec-once=flameshot
exec-once=firewall-applet

# Startup the foot terminal daemon for faster terminal launches
# exec-once = foot --server

# Setup Pipewire for OBS and ZOOM
# exec ~/.config/.scripts/ut-obszoom

# toggle_kmonad
# exec-once = $HOME/.config/.scripts/toggle_kmonad.sh
# exec-once =  kmonad $HOME/.config/kmonad/k350.kbd

# set bluelight filter
exec-once=~/.config/.scripts/ut-bluelight
# exec-once = wlsunset -t 2000 -T 2300
# exec-once = wlsunset -t 3000 -T 4000

# Load last wallpaper and waybar with pywal colors
# exec sleep 1 && $HOME/.config/.scripts/ut-wallpaper --init
exec-once=~/.config/.scripts/wb-launch

# no x here
# exec xwayland disable

# # set evviroment variables
# exec systemctl --user set-environment TERM=xterm-256color
