[[repos]]
url = "https://raw.githubusercontent.com/leftwm/leftwm-community-themes/master/known.toml"
name = "community"
definitions_version = 1

[[repos.themes]]
name = "Amber"
repository = "https://github.com/di-effe/amber"
commit = "*"
version = "0.2.2"
leftwm_versions = ">0.2.10, <0.3.0"
current = false

[[repos.themes]]
name = "arch-one-dark"
repository = "https://github.com/jamesbaker1901/leftwm-arch-one-dark/"
commit = "*"
version = "1.0.0"
leftwm_versions = "^0.3.0"
current = false

[[repos.themes]]
name = "Ascent"
directory = "/home/moosicmaan/.config/leftwm/themes/Ascent"
repository = "https://gitlab.com/mWalrus/ascent"
commit = "*"
version = "1.0.0"
leftwm_versions = ">0.2.7"
current = false

[[repos.themes]]
name = "Blue Coffee"
directory = "/home/moosicmaan/.config/leftwm/themes/Blue Coffee"
repository = "https://github.com/Qwart376/Blue-Coffee/"
commit = "*"
version = "0.0.1"
leftwm_versions = "<0.3.0"
current = false

[[repos.themes]]
name = "Bumblebee"
directory = "/home/moosicmaan/.config/leftwm/themes/Bumblebee"
repository = "https://github.com/mfdorst/leftwm-bumblebee/"
commit = "*"
version = "0.0.1"
leftwm_versions = "^0.2.8, <0.3.0"
current = false

[[repos.themes]]
name = "Catppuccin"
repository = "https://github.com/di-effe/catppuccin"
commit = "*"
version = "0.1.1"
leftwm_versions = ">0.2.10, <0.3.0"
current = false

[[repos.themes]]
name = "Coffee"
repository = "https://github.com/lex148/leftwm-coffee/"
commit = "*"
version = "0.0.1"
leftwm_versions = "<0.3.0"
current = false

[[repos.themes]]
name = "Dementive"
repository = "https://github.com/dementive/leftwm-dementive"
commit = "*"
version = "0.1"
leftwm_versions = "^0.4.0"
current = false

[[repos.themes]]
name = "Desire"
repository = "https://github.com/copypasteonly/Desire"
commit = "*"
version = "0.1"
leftwm_versions = "^0.4.0"
current = false

[[repos.themes]]
name = "Double Bar"
repository = "https://github.com/PeterDauwe/doublebar/"
commit = "*"
version = "0.0.2"
leftwm_versions = "^0.3.0"
current = false

[[repos.themes]]
name = "Dracula Rounded"
repository = "https://github.com/AethanFoot/leftwm-theme-dracula-rounded/"
commit = "*"
version = "0.0.3"
leftwm_versions = "^0.3.0"
current = false

[[repos.themes]]
name = "Epitaph"
directory = "/home/moosicmaan/.config/leftwm/themes/Epitaph"
repository = "https://github.com/VentGrey/Epitaph"
commit = "*"
version = "0.0.2"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "Flamingo"
directory = "/home/moosicmaan/.config/leftwm/themes/Flamingo"
repository = "https://github.com/necaris/leftwm-theme-flamingo"
commit = "*"
version = "0.0.1"
leftwm_versions = ">0.2.7, <0.3.0"
current = false

[[repos.themes]]
name = "Forest"
repository = "https://github.com/lex148/forest/"
commit = "*"
version = "0.0.1"
leftwm_versions = "^0.3.0"
current = false

[[repos.themes]]
name = "Garden"
directory = "/home/moosicmaan/.config/leftwm/themes/Garden"
repository = "https://github.com/taylor85345/leftwm-theme-garden"
commit = "*"
version = "0.0.4"
leftwm_versions = ">0.2.7"
current = false

[[repos.themes]]
name = "Ground Zero"
directory = "/home/moosicmaan/.config/leftwm/themes/Ground Zero"
repository = "https://github.com/Qwart376/Ground-Zero/"
commit = "*"
version = "0.0.1"
leftwm_versions = "<0.3.0"
current = false

[[repos.themes]]
name = "minimal-solarized"
repository = "https://github.com/minda1975/minimal_solarized"
commit = "*"
version = "0.1.0"
leftwm_versions = "^0.3.0"
current = false

[[repos.themes]]
name = "Molese"
directory = "/home/moosicmaan/.config/leftwm/themes/Molese"
repository = "https://github.com/m0lese/leftwm-config"
commit = "*"
version = "2.1.0"
leftwm_versions = ">0.2.10, <0.3.0"
current = false

[[repos.themes]]
name = "Ocean-night"
directory = "/home/moosicmaan/.config/leftwm/themes/Ocean-night"
repository = "https://github.com/TheRoniOne/ocean-night"
commit = "*"
version = "0.0.1"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "Orange Forest"
repository = "https://github.com/PVautour/leftwm-theme-orange-forest/"
commit = "*"
version = "0.0.2"
leftwm_versions = "^0.3.0"
current = false

[[repos.themes]]
name = "plan9"
repository = "https://github.com/seabassapologist/leftwm-theme-plan9"
commit = "*"
version = "0.1.0"
leftwm_versions = "^0.3.0"
current = false

[[repos.themes]]
name = "Red Moon"
directory = "/home/moosicmaan/.config/leftwm/themes/Red Moon"
repository = "https://github.com/Qwart376/Red-Moon"
commit = "*"
version = "0.0.1"
leftwm_versions = "<0.3.0"
current = false

[[repos.themes]]
name = "Serika"
directory = "/home/moosicmaan/.config/leftwm/themes/Serika"
repository = "https://github.com/VuiMuich/leftwm-theme-serika.git"
commit = "*"
version = "0.0.1"
leftwm_versions = ">=0.3.0"
current = false

[[repos.themes]]
name = "Soothe"
repository = "https://github.com/b4skyx/leftwm-soothe/"
commit = "*"
version = "0.0.1"
leftwm_versions = "<0.3.0"
current = false
relative_directory = "theme/"

[[repos.themes]]
name = "SpaceJelly"
repository = "https://gitlab.com/leftwmthemes/space_jelly"
commit = "*"
version = "1.0.0"
leftwm_versions = ">0.2.10, <0.3.0"
current = false

[[repos.themes]]
name = "sunflower"
repository = "https://github.com/mautamu/leftwm-sunflower/"
commit = "*"
version = "0.1.2"
leftwm_versions = "^0.2.11, <0.3.0"
current = false

[[repos.themes]]
name = "Sunset"
directory = "/home/moosicmaan/.config/leftwm/themes/Sunset"
repository = "https://github.com/Syudagye/leftwm-sunset"
commit = "*"
version = "0.0.1"
leftwm_versions = "<0.3.0"
current = false

[[repos.themes]]
name = "TNG"
repository = "https://github.com/lex148/leftwm-tng/"
commit = "*"
version = "0.0.1"
leftwm_versions = "<0.3.0"
current = false

[[repos.themes]]
name = "Windows XP"
repository = "https://github.com/lex148/leftwm-windowsxp/"
commit = "*"
version = "0.0.1"
leftwm_versions = "<0.3.0"
current = false

[[repos.themes]]
name = "Zexanima"
repository = "https://github.com/calebgasser/zexanima-leftwm-theme/"
commit = "*"
version = "0.0.1"
leftwm_versions = ">0.3.0"
current = false

[[repos.themes]]
name = "Blood-Moon"
directory = "/home/moosicmaan/.config/leftwm/themes/Blood-Moon"
repository = "https://github.com/zawesomekid/Blood-Moon-leftwm-theme"
commit = "*"
version = "0.0.1"
leftwm_versions = ">0.3.0"
current = false

[[repos.themes]]
name = "Late-Night"
directory = "/home/moosicmaan/.config/leftwm/themes/Late-Night"
repository = "https://github.com/JacoMalan1/LateNight"
commit = "*"
version = "0.0.2"
leftwm_versions = ">0.3.0"
current = false

[[repos]]
url = "localhost"
name = "LOCAL"
definitions_version = 1

[[repos.themes]]
name = "kittycafe-sm"
directory = "/home/moosicmaan/.config/leftwm/themes/kittycafe-sm"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "eden"
directory = "/home/moosicmaan/.config/leftwm/themes/eden"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "sb-horror"
directory = "/home/moosicmaan/.config/leftwm/themes/sb-horror"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "shades"
directory = "/home/moosicmaan/.config/leftwm/themes/shades"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "db-nemesis"
directory = "/home/moosicmaan/.config/leftwm/themes/db-nemesis"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "docky"
directory = "/home/moosicmaan/.config/leftwm/themes/docky"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "material"
directory = "/home/moosicmaan/.config/leftwm/themes/material"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "db-scifi"
directory = "/home/moosicmaan/.config/leftwm/themes/db-scifi"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "doublebar"
directory = "/home/moosicmaan/.config/leftwm/themes/doublebar"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "space"
directory = "/home/moosicmaan/.config/leftwm/themes/space"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "forest"
directory = "/home/moosicmaan/.config/leftwm/themes/forest"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "pi"
directory = "/home/moosicmaan/.config/leftwm/themes/pi"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "starwars"
directory = "/home/moosicmaan/.config/leftwm/themes/starwars"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "grayblocks"
directory = "/home/moosicmaan/.config/leftwm/themes/grayblocks"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "parker"
directory = "/home/moosicmaan/.config/leftwm/themes/parker"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "kittycafe-dm"
directory = "/home/moosicmaan/.config/leftwm/themes/kittycafe-dm"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "db-comic"
directory = "/home/moosicmaan/.config/leftwm/themes/db-comic"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "fancy"
directory = "/home/moosicmaan/.config/leftwm/themes/fancy"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "mesh"
directory = "/home/moosicmaan/.config/leftwm/themes/mesh"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "db-color-dev"
directory = "/home/moosicmaan/.config/leftwm/themes/db-color-dev"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "smooth"
directory = "/home/moosicmaan/.config/leftwm/themes/smooth"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "db"
directory = "/home/moosicmaan/.config/leftwm/themes/db"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "matrix"
directory = "/home/moosicmaan/.config/leftwm/themes/matrix"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "arise"
directory = "/home/moosicmaan/.config/leftwm/themes/arise"
version = "0.0.0"
leftwm_versions = "*"
current = true

[[repos.themes]]
name = "Changed Sunset"
directory = "/home/moosicmaan/.config/leftwm/themes/Changed Sunset"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "halo"
directory = "/home/moosicmaan/.config/leftwm/themes/halo"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "db-scifi-star"
directory = "/home/moosicmaan/.config/leftwm/themes/db-scifi-star"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "greyblocks"
directory = "/home/moosicmaan/.config/leftwm/themes/greyblocks"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "catppuccin"
directory = "/home/moosicmaan/.config/leftwm/themes/catppuccin"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "coffee"
directory = "/home/moosicmaan/.config/leftwm/themes/coffee"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "dementive"
directory = "/home/moosicmaan/.config/leftwm/themes/dementive"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "dracula-rounded"
directory = "/home/moosicmaan/.config/leftwm/themes/dracula-rounded"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "leftwm-arch-one-dark"
directory = "/home/moosicmaan/.config/leftwm/themes/leftwm-arch-one-dark"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "leftwm-sunflower"
directory = "/home/moosicmaan/.config/leftwm/themes/leftwm-sunflower"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "leftwm-theme-garden"
directory = "/home/moosicmaan/.config/leftwm/themes/leftwm-theme-garden"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "leftwm-theme-plan9"
directory = "/home/moosicmaan/.config/leftwm/themes/leftwm-theme-plan9"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "leftwm-theme-serika"
directory = "/home/moosicmaan/.config/leftwm/themes/leftwm-theme-serika"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "minimal_solarized"
directory = "/home/moosicmaan/.config/leftwm/themes/minimal_solarized"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "orangeforest"
directory = "/home/moosicmaan/.config/leftwm/themes/orangeforest"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "soothe"
directory = "/home/moosicmaan/.config/leftwm/themes/soothe"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "space_jelly"
directory = "/home/moosicmaan/.config/leftwm/themes/space_jelly"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "tng"
directory = "/home/moosicmaan/.config/leftwm/themes/tng"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "windowsxp"
directory = "/home/moosicmaan/.config/leftwm/themes/windowsxp"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "zexanima-leftwm-theme"
directory = "/home/moosicmaan/.config/leftwm/themes/zexanima-leftwm-theme"
version = "0.0.0"
leftwm_versions = "*"
current = false
