VIA_ENABLE          = yes
VIAL_ENABLE         = yes
LTO_ENABLE          = yes
VIALRGB_ENABLE      = yes
# RGBLIGHT_ENABLE     = yes
# RGB_MATRIX_ENABLE   = no # Can't have RGBLIGHT and RGB_MATRIX at the same time.
MOUSEKEY_ENABLE     = yes
EXTRAKEY_ENABLE     = yes
OLED_ENABLE         = no
# OLED_DRIVER         = SSD1306
COMBO_ENABLE        = yes
QMK_SETTINGS        = yes
REPEAT_KEY_ENABLE   = yes
CAPS_WORD_ENABLE    = yes
ENCODER_MAP_ENABLE  = no
LAYER_LOCK_ENABLE   = no
NUM_LOCK_ENABLE     = no
