#!/usr/bin/env bash

# note the use of the comma in the fllowing

for file in /{,usr/}bin/*calc; do #             ^    Find all executable files ending in "calc"
    #+                 in /bin and /usr/bin directories.
    if [ -x "$file" ]; then
        echo "$file"
    fi
done

echo "------------------------------------------->"
t2=$((a = 9, 15 / 3))
# Set "a = 9" and "t2 = 15 / 3"
printf 't2 = %s and a = %s\n' "$t2" "$a"

echo "------------------------------------------->"
not_empty() {
    :
} # Contains a : (null command), and so is not empty.

echo "<not_empty returns $(not_empty) and evals $?>"

echo "------------------------------------------->"
# this is a cool way to create or refresh files
echo "BEFORE"
if [[ -f test.txt ]]; then
    echo "<test.txt is found>"
    echo "<contains: $(cat test.txt)>"
else
    echo "test.txt NOT found"
fi
: >test.txt
echo "AFTER"
if [[ -f test.txt ]]; then
    echo "<test.txt is found>"
    echo "<contains: $(cat test.txt)>"
    if [[ -s test.txt ]]; then
        echo "<the length is > 0"
    else
        echo "<the length is = 0"
    fi
else
    echo "test.txt NOT found"
fi
date >>test.txt
if [[ -s test.txt ]] \
    ; then # || or && <test>
    echo "<test.txt is now present and filled with a date:"
    echo "<contains: $(cat test.txt)>"
else
    echo "<test for file failed>"
fi
echo "------------------------------------------->"
# [[ Octal and hexadecimal evaluation ]]
# Thank you, Moritz Gronbach, for pointing this out.

decimal=15
octal=017 # = 15 (decimal)
hex=0x0f  # = 15 (decimal)

if [ "$decimal" -eq "$octal" ]; then
    echo "$decimal equals $octal"
else
    echo "$decimal is not equal to $octal" # 15 is not equal to 017
fi                                         # Doesn't evaluate within [ single brackets ]!

if [[ "$decimal" -eq "$octal" ]]; then
    echo "$decimal equals $octal" # 15 equals 017
else
    echo "$decimal is not equal to $octal"
fi # Evaluates within [[ double brackets ]]!

if [[ "$decimal" -eq "$hex" ]]; then
    echo "$decimal equals $hex" # 15 equals 0x0f
else
    echo "$decimal is not equal to $hex"
fi # [[ $hexadecimal ]] also evaluates!
echo "------------------------------------------->"
