-m
--tmux=75%
--margin=2%,2%
--scroll-off=3
--border=rounded
--layout=reverse
--border-label='╢ FZF Default ╟'
--preview 'bat -n --color=always {}'
--preview-label=' ~ Preview ~ '
--info=hidden
--header='<TAB> for MULTI'
--color='dark,border:bright-cyan,header:italic:yellow,prompt:yellow'
--preview-label=' ~ Preview ~ '
--prompt='FIND ▶ '
--pointer='→'
--marker='*'
--walker-skip=.git,node_modules,target,.bluemail,.thunderbird,.firedragon,.mozilla,BraveSoftware,.steam,.rustup,.cache,.local,emacs,heroic,.npm,.nuget,Heroic
