-m
--tmux=75%
--margin=2%,2%
--scroll-off=3
--border=rounded
--layout=reverse
--border-label='╢ FZF History ╟'
--preview 'echo {}'
--preview-label=' ~ Preview ~ '
--preview-window='right,40%,wrap'
--info=hidden
--header='<TAB> for MULTI'
--color='dark,border:bright-cyan,header:italic:yellow,prompt:yellow'
--preview-label=' ~ Preview ~ '
--prompt='FIND ▶ '
--pointer='→'
--marker='*'
