# =====================================================
# -----------------------------------------------------
# WORSPACE SETTINGS
# Dynamic file from ~/.config/.scripts/write_workspaces.sh
# -----------------------------------------------------
# =====================================================

workspace = 10, monitor:eDP-1, layout:scrolling, gapsout:0
workspace = 1, monitor:eDP-1, layout:dwindle, default:1
workspace = 2, monitor:eDP-1, layout:scrolling, gapsout:0
workspace = 3, monitor:eDP-1, layout:scrolling, gapsout:0
workspace = 4, monitor:HDMI-A-1, layout:scrolling, gapsout:0
workspace = 5, monitor:HDMI-A-1, layout:dwindle
workspace = 6, monitor:HDMI-A-1, layout:dwindle, default:1
workspace = 7, monitor:HDMI-A-1, layout:dwindle 
workspace = 8, monitor:HDMI-A-1, layout:dwindle 
workspace = 9, monitor:HDMI-A-1, layout:dwindle 
