# =====================================================
# -----------------------------------------------------
# WORSPACE SETTINGS
# Dynamic file from ~/.config/.scripts/write_workspaces.sh
# -----------------------------------------------------
# =====================================================

workspace = 10, monitor:eDP-1, layout: scrolling
workspace = 1, monitor:eDP-1, default:true, layout: scrolling
workspace = 2, monitor:eDP-1, layout:scrolling
workspace = 3, monitor:eDP-1, layout: scrolling
workspace = 4, monitor:HDMI-A-1, layout: dwindle 
workspace = 5, monitor:HDMI-A-1, layout: scrolling 
workspace = 6, monitor:HDMI-A-1, default:true, layout: dwindle 
workspace = 7, monitor:HDMI-A-1, layout: dwindle 
workspace = 8, monitor:HDMI-A-1, layout: dwindle 
workspace = 9, monitor:HDMI-A-1, layout: dwindle 
