[color]
# Colors can be one of seven predefined: black, blue, cyan, green, magenta, red, white, yellow.
# Or defined by hex code '#xxxxxx' (hex code must be within ''). User defined colors require
# a terminal that can change color definitions such as Gnome-terminal or rxvt.
# default is to keep current terminal color
; background = default
; foreground = default

# SDL and sdl_glsl only support hex code colors, these are the default:
background = '{background}'
; foreground = '{foreground}'

# Gradient mode, only hex defined colors are supported,
# background must also be defined in hex or remain commented out. 1 = on, 0 = off.
# You can define as many as 8 different colors. They range from bottom to top of the screen
gradient = 1
gradient_color_0 = '{color0}'
gradient_color_1 = '{color1}'
gradient_color_2 = '{color2}'
gradient_color_3 = '{color3}'
gradient_color_4 = '{color4}'
gradient_color_5 = '{color5}'
gradient_color_6 = '{color6}'
gradient_color_7 = '{color7}'

# Horizontal is only supported on noncurses output.
# Only one color will be calculated per bar.
horizontal_gradient = 1
horizontal_gradient_color_1 = '{color8}'
horizontal_gradient_color_2 = '{color9}'
horizontal_gradient_color_3 = '{color10}'
horizontal_gradient_color_4 = '{color11}'
horizontal_gradient_color_5 = '{color12}'
horizontal_gradient_color_6 = '{color13}'
horizontal_gradient_color_7 = '{color14}'
horizontal_gradient_color_8 = '{color15}'

# If both vertical and horizontal gradients are enabled, the vertical one will be blended in this direction.
# Can be 'up', 'down', 'left' or 'right'. 'up' means the vertical gradient will be blended in from
# bottom to top. I.e. the bottom will only be the horizontal
# and top will only be the vertical color of the gradient.
; blend_direction = 'left'
