return {
  -- Extra themes
  { "ellisonleao/gruvbox.nvim", name = "gruvbox", lazy = false, priority = 1000 },
  { "rebelot/kanagawa.nvim", name = "kanagawa", lazy = false, priority = 1000 },
  { "edeneast/nightfox.nvim", name = "nightfox", lazy = false, priority = 1000 },
  { "bluz71/vim-moonfly-colors", name = "moonfly", lazy = false, priority = 1000 },
  { "bluz71/vim-nightfly-colors", name = "nightfly", lazy = false, priority = 1000 },
  { "abstract-ide/abstract-cs", name = "abstract", lazy = false, priority = 1000 },
  { "daltonmenezes/aura-theme", name = "aura", lazy = false, priority = 1000 },
  { "projekt0n/github-nvim-theme", name = "gitbub-theme", lazy = false, priority = 1000 },
  { "ayaz-amin/cyberpunk.nvim", name = "cyberpunk", lazy = false, priority = 1000 },
  {
    "LazyVim/LazyVim",
    opts = {
      -- colorscheme = "tokyonight-night",
      -- colorscheme = "moonfly",
      -- colorscheme = "cyberpunk",
      -- colorscheme = "abscs",
      colorscheme = "nightfly",
      -- colorscheme = "kanagawa",
      -- colorscheme = "kanagawa-dragon",
      -- colorscheme = "abscs",
      -- colorscheme = "retrobox",
      -- colorscheme = "pywal",
      -- colorscheme = "pablo",
      -- colorscheme = "gruvbox",
      -- colorscheme = "murphy",
      -- colorscheme = "elflord",
      -- colorscheme = "slate",
      -- colorscheme = "default",
      -- colorscheme = "catppuccin-mocha",
      -- colorscheme = "wildcharm",
      -- colorscheme = "koehler",
      -- colorscheme = "industry",
    },
  },
  -- Other theme plugins
}
