return {
  -- Extra themes
  { "ellisonleao/gruvbox.nvim", name = "gruvbox", lazy = true, priority = 5000 },
  { "rebelot/kanagawa.nvim", name = "kanagawa", lazy = true, priority = 5000 },
  { "edeneast/nightfox.nvim", name = "nightfox", lazy = true, priority = 5000 },
  { "bluz71/vim-moonfly-colors", name = "moonfly", lazy = true, priority = 5000 },
  { "bluz71/vim-nightfly-colors", name = "nightfly", lazy = true, priority = 5000 },
  { "abstract-ide/abstract-cs", name = "abstract", lazy = true, priority = 5000 },
  { "daltonmenezes/aura-theme", name = "aura", lazy = true, priority = 5000 },
  { "projekt0n/github-nvim-theme", name = "gitbub-theme", lazy = true, priority = 5000 },
  { "ayaz-amin/cyberpunk.nvim", name = "cyberpunk", lazy = true, priority = 5000 },
  { "scottmckendry/cyberdream.nvim", name = "cyberdream", lazy = true, priority = 5000 },
  { "alphaTechnolog/pywal.nvim", name = "pywal", lazy = true, priority = 5000 },
  { "shaunsingh/nord.nvim", name = "nord", lazy = true, priority = 5000 },
  { "Mofiqul/dracula.nvim", name = "dracula", lazy = true, priority = 5000 },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "nord",
      -- colorscheme = "dracula",
      -- colorscheme = "tokyonight-night",
      -- colorscheme = "github_dark_high_contrast",
      -- colorscheme = "github_dark_tritanopia",
      -- colorscheme = "moonfly",
      -- colorscheme = "cyberdream",
      -- colorscheme = "cyberpunk",
      -- colorscheme = "abscs",
      -- colorscheme = "nightfly",
      -- colorscheme = "kanagawa",
      -- colorscheme = "kanagawa-dragon",
      -- colorscheme = "abscs",
      -- colorscheme = "carbonfox",
      -- colorscheme = "pywal",
      -- colorscheme = "pablo",
      -- colorscheme = "gruvbox",
      -- colorscheme = "murphy",
      -- colorscheme = "elflord",
      -- colorscheme = "slate",
      -- colorscheme = "default",
      -- colorscheme = "catppuccin-mocha",
      -- colorscheme = "wildcharm",
      -- colorscheme = "koehler",
      -- colorscheme = "industry",
    },
  },
  -- Other theme plugins
}
