#!/usr/bin/env bash

echo -e "Hi $LOGNAME!\nNo Worries...\nYou are on $(uname) ;-)"

cat >scriptOUT <<"EOF"
# Begin /etc/fstab

# file system  mount-point  type     options             dump  fsck
#                                                              order

/dev/<xxx>     /            <fff>    defaults            1     1
/dev/<yyy>     swap         swap     pri=1               0     0

# End /etc/fstab
EOF
