#!/usr/bin/env bash

data="a  b   c"
echo "$data" | while read -r A B C; do echo -e "|$A|$B||$C|"; done
echo "$data" | while IFS= read -r A B C; do echo -e "|$A|$B||$C|"; done
echo "$data" | while IFS='a' read -r A B C; do echo -e "|$A|$B||$C|"; done
echo "$data" | while IFS='ab' read -r A B C; do echo -e "|$A|$B||$C|"; done
echo "$data" | while IFS='abc' read -r A B C; do echo -e "|$A|$B||$C|"; done
echo "$data" | while IFS=' ' read -r A B C; do echo -e "|$A|$B||$C|"; done

# 1	|a|b||c|
# 2	|a  b   c||||
# 3	||  b   c|||
# 4	||  ||   c|
# 5	||  ||   |
# 6	|a|b||c|
echo -e "-------------------->\n\n"

echo 'trying...'
while read -r A B C; do echo -e "|$A|$B||$C|"; done < <(echo "$data")
while IFS= read -r A B C; do echo -e "|$A|$B||$C|"; done < <(echo "$data")
while IFS='a' read -r A B C; do echo -e "|$A|$B||$C|"; done < <(echo "$data")
while IFS='ab' read -r A B C; do echo -e "|$A|$B||$C|"; done < <(echo "$data")
while IFS='abc' read -r A B C; do echo -e "|$A|$B||$C|"; done < <(echo "$data")
while IFS=' ' read -r A B C; do echo -e "|$A|$B||$C|"; done < <(echo "$data")

# trying...
# 1	|a|b||c|
# 2	|a  b   c||||
# 3	||  b   c|||
# 4	||  ||   c|
# 5	||  ||   |
# 6	|a|b||c|
echo -e "-------------------->\n\n"

# echo -e "/etc/passwd is:\n$(cat /etc/passwd)"
# echo -e "/etc/passwd is:\n$(cat /etc/passwd)"
echo "my read of /etc/passwd is:"
while IFS=: read -r user _ _ _ des _; do
    echo -e "found user:\t$user - $des"
done </etc/passwd
echo -e "-------------------->\n\n"

# echo -e "/etc/passwd is:\n$(cat /etc/passwd)"
echo "my read of /etc/passwd is:"
while IFS=: read -r line; do
    cutline=$(echo "$line" | cut -d : --output-delimiter ' - ' -f 1,5)
    echo -e "found user:\t$cutline"
done </etc/passwd
echo -e "-------------------->\n\n"

# Source - https://superuser.com/a/781774
# Posted by Val
# Retrieved 2026-03-21, License - CC BY-SA 3.0

while IFS="," read -ra items; do
    for item in "${items[@]}"; do
        for i in {1..3}; do
            printf '%d %s\n' "$i" "$item"
        done
    done
done <<<"Hello World,Questions,Answers"

# 1 Hello World
# 2 Hello World
# 3 Hello World
# 1 Questions
# 2 Questions
# 3 Questions
# 1 Answers
# 2 Answers
# 3 Answers
echo -e "-------------------->\n\n"

echo " this   is a test         " | while IFS= read -r line; do echo "=$line="; done
# = this   is a test =
echo " this   is a test         " | while IFS='|' read -r line; do echo "=$line="; done
# = this   is a test =
echo " this   is a test         " | while read -r line; do echo "=$line="; done
# =this   is a test=
echo " this   is a test         " | while IFS= read -r w1 w2 w3 w4; do echo "=$w1 $w2 $w3 $w4="; done
# = this   is a test            =
echo " this   is a test         " | while read -r w1 w2 w3 w4; do echo "=$w1 $w2 $w3 $w4="; done
# =this is a test=
