format = '$username$hostname$jobs$directory$sudo$git_status$fill$cmd_duration$all'
# format = '$username$hostname$jobs$directory$sudo$git_status$all'
right_format = "$time"
add_newline = false

## FIRST LINE/ROW: Info & Status
# First param ─┌
[username]
# format = " [╭─$user]($style)@"
format = " ╔══ [$user]($style)"
show_always = true
style_root = "underline bg:#bf5700"
# style_user = "bold white"
style_user = "purple"
# style_user = "underline bg:#bf5700"
# aliases = { "moosicmaan" = "me" }

[hostname]
ssh_only = true
format = "[@$hostname](bold blue) "
disabled = false

# Second param
[jobs]
threshold = 1
symbol_threshold = 1
number_threshold = 1
format = "[$symbol$number]($style)"
symbol = "✦"
style = "bold blue"
disabled = false

# Third param
[directory]
style = "purple"
format = ' in [$path]($style) [$read_only]($read_only_style)'
truncate_to_repo = true
truncation_length = 0
truncation_symbol = "repo: "

# Fourth param
[sudo]
format = "[as $symbol]($style)"
# symbol = "🧙 "
symbol = "🛠️ "
style = "bold blue"
allow_windows = false
disabled = false

# Fifth param
# Before all the version info (python, nodejs, php, etc.)
[git_status]
disabled = false
format = '([\[$all_status$ahead_behind\]]($style) )'
modified = "!${count}"
# ahead = "⇡${count}"
# behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
deleted = "x"
conflicted = "="
stashed = '\$'
renamed = "»"
staged = "+"
untracked = "?"
typechanged = ""
up_to_date = ""
ignore_submodules = false
style = "red bold"

# Last param in the first line/row
[cmd_duration]
disabled = false
format = "took [$duration]($style) "
min_time = 1


## SECOND LINE/ROW: Prompt
# Somethere at the beginning
[battery]
charging_symbol = ""
disabled = true
discharging_symbol = ""
full_symbol = ""

[[battery.display]] # "bold red" style when capacity is between 0% and 10%
style = "bold red"
threshold = 15

[[battery.display]] # "bold yellow" style when capacity is between 10% and 30%
style = "bold yellow"
threshold = 50

[[battery.display]] # "bold green" style when capacity is between 10% and 30%
style = "bold green"
threshold = 80

# Prompt: optional param 1
[time]
disabled = false
# format = " 🕙 $time($style)"
format = " $time($style) "
style = "bright-white"
time_format = "%T"

# Prompt: param 2
[character]
# error_symbol = " [× ](bold red)"
error_symbol = "[═](white)[⮚](bold red)"
# success_symbol = " [╰─λ](bold red)"
success_symbol = "[ ╚═](white)[⮚](#78b892)"
# vimcmd_symbol = "[ ╚═❮](white)"
vimcmd_symbol = "[ ╚═](white)[](#78b892)"

# Filler
[fill]
symbol = ' '
style = 'bold green'

# SYMBOLS
[status]
disabled = false
format = '[\[$symbol$status_common_meaning$status_signal_name$status_maybe_int\]]($style)'
map_symbol = true
pipestatus = true
# symbol = "🔴"
symbol = "‼️"

[aws]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
format = "on [$symbol$branch(:$remote_branch)]($style) "
symbol = " "
style = "bold purple"
truncation_length = 9223372036854775807
truncation_symbol = "…"
only_attached = false
always_show_remote = false
ignore_branches = []
disabled = false

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "
